export const APP_ROUTES = {
    HOME: '',
    LOGIN: '/login',
    FORBIDDEN: '/forbidden',
    SERVER_ERROR: '/server-error',
    KITCHEN: '/kitchen',
    WAITER: '/waiter',
    CASHIER: '/cashier',
    STATUS_DISPLAY: '/status',
    MANAGER: '/manager',
    MANAGER_MENU: '/manager/menu',
    MANAGER_TABLES: '/manager/tables',
    MANAGER_ORDERS: '/manager/orders',
    MANAGER_HISTORY: '/manager/orders',
    MANAGER_USERS: '/manager/users',
    MANAGER_RESTAURANTS: '/manager/restaurants',
    MANAGER_LIVE_ORDERS: '/manager/live-orders',
    ADMIN: '/admin',
    ADMIN_RESTAURANTS: '/admin/restaurants',
    ADMIN_USERS: '/admin/users',
    ADMIN_LIVE_ORDERS: '/admin/live-orders',
    ADMIN_LOGS: '/admin/logs',
    ADMIN_ANALYTICS: '/admin/analytics',
    ADMIN_CURRENCIES: '/admin/currencies',
    ADMIN_ORDERS: '/admin/orders',
    ADMIN_TABLES: '/admin/tables',
    ADMIN_MENU: '/admin/menu',
} as const;
