<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Foodlyn.Shared\Foodlyn.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\Commands\CancelOrder\" />
    <Folder Include="Application\Commands\CreateOrder\" />
    <Folder Include="Application\DTOs\" />
    <Folder Include="Application\EventHandlers\" />
    <Folder Include="Application\Repositories\" />
    <Folder Include="Application\Services\" />
    <Folder Include="Application\Validators\" />
    <Folder Include="Domain\Entities\" />
    <Folder Include="Domain\Enums\" />
    <Folder Include="Infrastructure\Configurations\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
